### ISSUE TITLE
data.0.meta.title must be a string

### ISSUE THREAD

**Issue by matto49** [mx-space/mx-admin#738]
### Describe the bug

proxy/qaqdmin#/other/markdown
markdown导入导出时，yaml字段被成功识别，同时包含title字段，但是会报这个错误。

### Reproduction

/api/v2/markdown/import接口

markdown示例:
```md
---
date: '2023/3/28 14:00'
coverUrl: 'https://s3.bmp.ovh/imgs/2023/03/28/932ba869aceb2776.jpg'
sticky: false
keyword: css
description: study
title: 操作系统原理实验
tag: [国示院]
categories: [study]  
---

## 第一次实验

操作系统原理这门课还是挺有意识的，这里主要记录一下操作系统原理实验的一些操作
```

### System Info

Ubuntu-20.04

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Innei** [comment]
Fixed in #740
